The blood bank wants to determine the least expensive way to transport available blood donations, from Pittsburgh and Staunton to hospitals in Charleston, Roanoke, Norfolk, and Suffolk.  The supply and Demand for donated blood is shown in fig 5.36 along with the unit cost of shipping along each possible arc.
a) create a spreadsheet model for this problem?
b) What is the optimal solution?
c) Suppose that no more than  1000 units of blood can be transported over any one  arc. what is the solution to the revised problem? 

explain step by steps in detail.
Uploaded image preview
